# Generated by Django 3.0.4 on 2020-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200408_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
