# Generated by Django 3.0.5 on 2020-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200409_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='c_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
